panel_jwt_auth_secret: ENC[AES256_GCM,data:E85mWnwwT80mNb5QYyjnsHl7pFlC7T1THvxRLnwH629Wshnz8bpYPcKuZQrU/CJNvY33t5VHoNq5OzFU+qq08Q==,iv:0Vg3KLA+vbMsmIN88FTSw7ylaxT11cmBLPw0b76SHrU=,tag:oQyIdHrcizrE/0SalDlcyA==,type:str]
panel_jwt_api_tokens_secret: ENC[AES256_GCM,data:dYRSdRFxQc+0deBHHuOSVxgvMzP+H2xMbh9ifEJXOo+NIF4bGGCUTWhoguwoDo3Dbbk6VWH5z6GNBWpSjD4k5w==,iv:abdb52fmgleLjHpG0whA4V5aYxJr2MHd+TjVTIlyA9g=,tag:V7qtu0Vg+EVeBqHW+WUq0g==,type:str]
panel_postgres_password: ENC[AES256_GCM,data:jOtfN5p6+Ijt2T8FIhmO947BXkBdu2ibvPwBv7LOr8o=,iv:+aJcmh86Wdszpyl7mK+4vjWXRnymP2zSbgoWMJkjiig=,tag:6HRg0WzkuH9gmWutN3OJLw==,type:str]
panel_metrics_password: ENC[AES256_GCM,data:dBjfSIKJTwYwkHwTzDzv/rkGKuw07nEabJGiXfgatYs=,iv:JXqL7QBBjLLQTq9GVUG+FtSTxN0DuhOfBdsXtBbeK78=,tag:FlZEW6Vy/LTpJMpOhPzKSA==,type:str]
mesh_cookie_secret: ENC[AES256_GCM,data:NsWyl61dw0yM0WdpSPVCHFpao/v0rksMi/wN8r8D2Zo=,iv:cy1FDwFfETVVVR6Vx/sdWYzhsr9V8uDV23fQW3Pn2IY=,tag:rsXnc2WNCmJRgKrGXMdgbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaeEF3SnNjeTIxY25sNUdU
            djRPbFZOWE5TZlF4a0hmczhaSXg0V0ZjTGo0CmVlQVVzUzRMbW5UVHFjUTN4M0V2
            K3l4MVhoY0hPZjRjVzg2TjREVzZPZjAKLS0tIEJmT3M2Yi9uWmxvTTRLanBOcXVY
            TVFIcHp4aFpzakFRUGVXT1RBYTBWVFUK4iwFwYDyT9uhzc4hRs6n2ieYkyrZ7SwN
            Rys2+k7h9CeUSC1bJAW+lP/87/zUH1PBeuhm1DGGCCHNK4ClwiT2VQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r7w9d59dtx5ksqxfujskjk5xwrt4ftv5czva2zzff2paggggy9nq4q0lxm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOXNqWlRGdTl2Ulpnc1VP
            SnVWODZZVGpjc3EzZTVhb3BLNlJFN2diMUFzCmJCRmlTUk05a01pU1haZ1hwaHk3
            STNPb2FidlVRR3JuQ1lNMW1aYUtFN0UKLS0tIG1ncUdib3hLd2xuTTNKaGpZVkRD
            VzZtUVVhcU5vMHVrSXQwbGNZa0VjWUEKS1WvoJey88orXXxQpWUASzFAQekTRBdV
            xjP8i2hV66CkF2ZomwwyJNk+kG3TggvUiWbODKHQVyQgIba8fnENJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15senurg48rul7qhfq7s58grxd84ku4rgpx3qjvegn9hvdh7s84fq5d5qag
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDc3dlOGxYOENUaDZvNXlW
            SnV5dlhmOGRPTWhmMG9ia0RtaEFyZmJHdDBNCnRXM3lIalhRL29IZ1NrSURxMXYz
            SkEzLzFQdHhRNGZ3YURXZDF4aVlUeG8KLS0tIC8wQVdmdGw0c1FSbUpmWUpQRDJs
            aGIwVGJiaDRjd01hYWRmTDVkZmxwTmcKbwys5PwGh54ZPy3ak6lFupS9v/S9qIhM
            lCdKe8ejytcy91tUpzT83HgJdOIxD4OyBPmv4XkONKcndi8xTaznsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1grp3kmtu48stpw82xwnugpppv5ej4gtqpra6fprt0lt9gqmfdc0qy0pmm5
    lastmodified: "2026-07-29T20:23:47Z"
    mac: ENC[AES256_GCM,data:p+aAE+0mHpllJv9XxcYKVfuomB/kXFElXRJwPTNPaULqC7PE/8WH++Pk9v/fPHwzrqsg4ANIiS2hpIOhB0WA5VzAcMNvfE81s6SrH+yeTAhuDec/FiNteHQ+wLRYSLQhe7edmAFJwZ1JdLszHlUnGPdXJo5YjFhmXM9InTHQgEY=,iv:IxPdmlvlRna4dDYgG5Qg3w8OMnITlnZsYsccVNRGZNA=,tag:n8l7Ly9PUP1aVgH3zIW9Fw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
